name: Build Lab Projects

on:
  push:
  schedule:
    - cron: "0 5 * * SUN"

jobs:
  build-maven-projects:
    strategy:
      fail-fast: false
      matrix:
        module:
          [
            "learning-module-1",
            "learning-module-2",
            "learning-module-3",
            "learning-module-4",
            "learning-module-5",
            "learning-module-6",
          ]
    runs-on: ubuntu-latest
    name: Build Maven Project for ${{ matrix.module }}

    steps:
      - name: VCS checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: adopt
          cache: maven

      - name: Build Mavne project
        working-directory: labs/${{ matrix.module }}
        run: ./mvnw verify
